# cherry dialect statix

disabled = [
  "collapsible_let_in",
  "eta_reduction",
  "manual_inherit",
  "manual_inherit_from",
  "useless_parens"
]

ignore = [
  "**/default.nix",
  "lib/default.nix"
]

enabled = [
  "bool_comparison",
  "empty_let_in",
  "legacy_let_syntax",
  "empty_pattern",
  "redundant_pattern_bind",
  "unquoted_uri",
  "deprecated_is_null",
  "empty_inherit",
  "faster_groupby",
  "faster_zipattrswith",
  "deprecated_to_path",
  "bool_simplification",
  "useless_has_attr",
  "empty_list_concat",
  "repeated_keys"
]
