# .github/workflows/ci.yml
name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/ci.yml"
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  build-config:
    strategy:
      matrix:
        include:
          - hostName: grovebringer
            nixosCfgKey: grovebringer
            homeCfgKey: grovebringer
            os-label: ubuntu-latest
          - hostName: aureliteiron
            nixosCfgKey: aureliteiron
            homeCfgKey: aureliteiron
            os-label: ubuntu-latest
      fail-fast: false

    name: Build ${{ matrix.hostName }}
    runs-on: ${{ matrix.os-label }}
    steps:
      - name: Free diskspace
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /nix
          root-reserve-mb: 5120
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - uses: actions/checkout@v4

      - name: Install Nix with experimental features
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - name: Restore and cache Nix store
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-store-${{ runner.os }}-
            nix-store-

      - name: Build NixOS Configuration
        if: ${{ contains(toJSON(matrix), 'nixosCfgKey') && matrix.nixosCfgKey != '' }}
        run: nix build .#nixosConfigurations.${{ matrix.nixosCfgKey }}.config.system.build.toplevel --extra-experimental-features 'nix-command flakes pipe-operators'