name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "flake.lock"
      - ".github/workflows/ci.yml"

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes pipe-operators

      - name: Check Flake
        run: nix flake check --keep-going

  build-config:
    needs: check-flake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - cherries
          - aureliteiron
      fail-fast: false
    name: Build ${{ matrix.host }}
    steps:
      - name: Free Disk Space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /nix
          root-reserve-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes pipe-operators

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.host }}-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ matrix.host }}-
          gc-max-store-size-linux: 2147483648
          purge: false

      - name: Build ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --print-build-logs
